title:  Elisabeth Ericson
logo: "/images/me.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  aka Eli (pronounced like "Ellie")
  <br><br>
  Master of Urban Spatial Analytics candidate (2022) at the University of Pennsylvania. 
  <br><br>
  I like maps, code, and concise self-descriptions.
  <br><br>
  <a href="https://www.linkedin.com/in/elisabethericson/">LinkedIn</a> 
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
